{% set name = "espnet" %}
{% set version = "202301" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/espnet-{{ version }}.tar.gz
  sha256: 424cc24a8ea37900761761598e985d9e02007813497ab23c5ea03ba3a87b9699

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 1

requirements:
  host:
    - numpy <=1.21.3
    - pip
    - pytest-runner
    - python {{ python_min }}
  run:
    - ci-sdr
    - configargparse >=1.2.1
    - ctc-segmentation >=1.6.6
    - editdistance >=0.6.2
    - espnet-tts-frontend
    - fast-bss-eval ==0.1.3
    - filelock
    - h5py >=2.10.0
    - humanfriendly
    - hydra-core >=1.3.2
    - importlib-metadata <5.0
    - jamo >=0.4.1
    - kaldiio >=2.17.0
    - librosa >=0.8.0
    - nltk >=3.4.5
    - opt-einsum >=3.0.0
    - protobuf <=3.20.1
    - pypinyin <=0.44.0
    - pysoundfile >=0.10.2
    - python >={{ python_min }}
    - pytorch >=1.3.0
    - pytorch-wpe
    - pyworld >=0.2.10
    - pyyaml >=5.1.2
    - scipy >=1.4.1
    - sentencepiece
    - torch-complex
    - typeguard ==2.13.3

test:
  imports:
    - espnet
    - espnet2
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/espnet/espnet
  summary: 'ESPnet: end-to-end speech processing toolkit'
  description: |
    ESPnet is an end-to-end speech processing toolkit covering end-to-end speech recognition, text-to-speech, speech translation, speech enhancement, speaker diarization, spoken language understanding, and so on. ESPnet uses pytorch as a deep learning engine and also follows Kaldi style data processing, feature extraction/format, and recipes to provide a complete setup for various speech processing experiments.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://espnet.github.io/espnet/
  dev_url: http://github.com/espnet/espnet

extra:
  recipe-maintainers:
    - wietsedv
